project:
  type: website
  output-dir: docs
  resources: 
    - "PAPERLongTermImpactofWaronLifeSatisfaction.xlsx"

website:
  title: "dataisdifficult.github.io"
  about:
    template: jolla
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - PAPERLongTermImpactofWaronLifeSatisfaction.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



